services:
  - type: web
    name: ai-poem-generator-backend
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: FRONTEND_URL
        value: https://your-frontend-domain.onrender.com
    healthCheckPath: /health
    autoDeploy: true